### PR TITLE
Fix inital ordering of experiments table

### LINKED ISSUE #3172: Created column is rendered the last by default
I think it's broken after the https://github.com/iterative/vscode-dvc/pull/3095

To reproduce - launch any new project (I was using Codespaces for that) and open the experiments table. In my case (and I've checked also locally) `Created` column is rendered at the very end.

### PR DESCRIPTION
**Pull request by mattseddon**
Fixes #3172

### CODE REVIEW

File: webview/src/experiments/util/buildColumns.tsx [hunk 1]
```diff
@@ -51,7 +51,7 @@ const getMainColumnProperties = (
         CellContext<Column, CellValue>
       >,
       header: () => <TimestampHeader />,
-      id: ColumnType.TIMESTAMP
+      id: 'Created'
```
Comment (mattseddon) [inline webview/src/experiments/util/buildColumns.tsx:54]: [F] This mismatched with the value provided in `columnOrder` which initially placed the column at the end of the table until any reordering added `id: 'timestamp'` to the table (and extension's) state.

Comment (mattseddon) [reply webview/src/experiments/util/buildColumns.tsx:54]: tricky one to track down

**Review by shcheklein — APPROVED** [review]
