### PR TITLE
Remove Studio data request failed Toast

### LINKED ISSUE #5120: Studio: if project doesn't exist, don't keep showing error
If I am connected to Studio but the project doesn't exist on Studio, I get an error that I can't get rid of like this:

https://github.com/iterative/vscode-dvc/assets/2308172/a24363a6-b50f-474b-bfa7-5d74dcbbd516

Can we stop repeatedly showing the error?

### PR DESCRIPTION
**Pull request by julieg18**
Removes the "Unable to fetch data from Studio" Toast since we try to fetch data periodically (meaning user could get this multiple times in a session)

Fixes #5120

### CODE REVIEW

File: extension/src/experiments/data/index.ts [hunk 1]
```diff
@@ -157,9 +156,6 @@ export class ExperimentsData extends BaseData<ExperimentsOutput> {
       })
     } catch {
       this.notifyChanged(defaultData)
-      void Toast.showError(
```
Comment (julieg18) [inline extension/src/experiments/data/index.ts:160]: We could add some logic to check if the user has already received the Toast and has a self-hosted URL, but that would add some extra complexity that I don't think is needed since we probably have few users using self-hosted URLs.

**Review by sroy3 — APPROVED** [review]

File: extension/src/experiments/data/index.ts (hunk 1 above)
Comment (shcheklein) [reply extension/src/experiments/data/index.ts:160]: We can have a health status in the Setup screen instead I think. If connection is failing we can a message, or even change it to "yellow" in the Setup screen. WDYT?
