### PR TITLE
Handle Git not being installed (Setup)

### LINKED ISSUE #4129: Setup screen is stuck on Loading ...
Fresh install, the latest extension release (1.0.6). Windows. 

Screenshot 2023-06-15 184245

```
......
[version: 1.0.6, 2023-06-16T01:44:27.165Z, pid: 12564] > dvc --version - INITIALIZED
[version: 1.0.6, 2023-06-16T01:44:27.197Z, pid: 12564] > dvc --version - FAILED with code 1 (47ms)
'dvc' is not recognized as an internal or external command,


operable program or batch file.


[version: 1.0.6, 2023-06-16T01:44:32.229Z, pid: 3956] > dvc --version - INITIALIZED
[version: 1.0.6, 2023-06-16T01:44:32.267Z, pid: 3956] > dvc --version - FAILED with code 1 (59ms)
'dvc' is not recognized as an internal or external command,


operable program or batch file.


[version: 1.0.6, 2023-06-16T01:44:32.287Z, pid: 16252] > dvc --version - INITIALIZED
[version: 1.0.6, 2023-06-16T01:44:32.316Z, pid: 16252] > dvc --version - FAILED with code 1 (48ms)
'dvc' is not recognized as an internal or external command,


operable program or batch file.


[version: 1.0.6, 2023-06-16T01:44:37.342Z, pid: 6300] > dvc --version - INITIALIZED
[version: 1.0.6, 2023-06-16T01:44:37.371Z, pid: 6300] > dvc --version - FAILED with code 1 (46ms)
'dvc' is not recognized as an internal or external command,


operable program or batch file.


[version: 1.0.6, 2023-06-16T01:44:37.388Z, pid: 4420] > dvc --version - INITIALIZED
[version: 1.0.6, 2023-06-16T01:44:37.421Z, pid: 4420] > dvc --version - FAILED with code 1 (48ms)
'dvc' is not recognized as an internal or external command,


operable program or batch file.
```

### PR DESCRIPTION
**Pull request by mattseddon**
# 2/2 `main` <- #4166 <- this

Closes #4129 by handling the edge case of the user not having Git installed when they try to get set up.

### CODE REVIEW

File: extension/src/setup/index.ts [hunk 1]
```diff
@@ -504,14 +511,21 @@ export class Setup
...
-      ))
-    } catch {
+    return !(await this.internalCommands.executeCommand<string | undefined>(
+      AvailableCommands.GIT_GET_REPOSITORY_ROOT,
+      cwd
+    ))
+  }
+
+  private async getIsGitAccessible() {
+    if (this.gitAccessible) {
```
Comment (mattseddon) [inline extension/src/setup/index.ts:521]: [F] If it is installed then don't check again. If users want to uninstall Git mid-session then that is their problem.

File: extension/src/cli/git/index.ts [hunk 2]
```diff
@@ -10,6 +10,9 @@ export class GitCli extends Cli {
       cwd
     })
 
-    return standardizePath(await this.executeProcess(options))
+    try {
+      const path = await this.executeProcess(options)
+      return standardizePath(path)
+    } catch {}
```
Comment (mattseddon) [inline extension/src/cli/git/index.ts:16]: [F] Need to be mindful of calling either CLI in Setup. We don't want things to crash before the users gets a chance to get setup.

**Review by julieg18 — APPROVED** [review]
Great work!
