### PR TITLE
Fix custom plots breaking with non-numeric values

### LINKED ISSUE #4625: `Custom plots`: Fail to render when selected parameter is not numeric
I created a custom plot by selecting a parameter containing different string values. The plot is empty:

Screenshot 2023-09-06 130254

However, I can export with `Save as JSON` and see the expected values:

```json
[
    {
        "id": "main",
        "metric": 0.9340795388735517,
        "param": "shufflenet_v2_x2_0"
    },
    {
        "id": "309c133",
        "metric": 0.8923946870030989,
        "param": "shufflenet_v2_x2_0"
    },
    {
        "id": "rimed-acre",
        "metric": 0.9288800744178878,
        "param": "squeezenet1_1"
    },
    {
        "id": "cadgy-loup",
        "metric": 0.9355338898522014,
        "param": "resnet34"
    },
    {
        "id": "tawie-moxa",
        "metric": 0.9305068735503278,
        "param": "alexnet"
    },
    {
        "id": "parky-many",
        "metric": 0.9340795388735517,
        "param": "shufflenet_v2_x2_0"
    }
]
```

Maybe we could create an index of unique values and use it as the horizontal axis while displaying the associated string as label?

### PR DESCRIPTION
**Pull request by julieg18**
## `main`

image

## PR

image

~Looks buggy due to the length of the param string, but that would not be a quick fix since I'd need to do some extra research on what we could do.~

Fixes #4625

### CODE REVIEW

File: extension/src/plots/model/custom.ts [hunk 1]
```diff
@@ -69,7 +69,16 @@ export const checkForCustomPlotOptions = (
   return false
 }
 
-export const createSpec = (title: string, metric: string, param: string) =>
+const getSpecDataType = (type: string) =>
+  type === 'number' ? 'quantitative' : 'nominal'
```
Comment (julieg18) [inline extension/src/plots/model/custom.ts:73]: When custom plots were first created, I had them set to `nominal` by default due to the fact that none-number values break on `quantitive`. Somewhere down the line, it must have changed back to `quantitive` 🤔.  I think it was because only `quantitive` orders the number values correctly.

File: extension/src/test/fixtures/expShow/base/customPlots.ts [hunk 2]
```diff
@@ -9,7 +9,7 @@ import { Experiment } from '../../../../experiments/webview/contract'
 export const customPlotsOrderFixture: CustomPlotsOrderValue[] = [
   {
     metric: 'summary.json:loss',
-    param: 'params.yaml:dropout'
+    param: 'params.yaml:log_file'
```
Comment (julieg18) [inline extension/src/test/fixtures/expShow/base/customPlots.ts:12]: I updated the fixture to include a string param for testing but this did lead me to touching practically every custom plots test, despite this being a rather small spec change 😅

**Review by mattseddon — APPROVED** [review]
Is it possible to change the angle of this axis label or truncate it?:

image

**Comment by mattseddon** [comment]
Take a look here: https://vega.github.io/vega-lite/docs/axis.html#labels

**Comment by julieg18** [comment]
> Is it possible to change the angle of this axis label or truncate it?:
> Take a look here: https://vega.github.io/vega-lite/docs/axis.html#labels

Thanks, I now see I can adjust label and title padding, fixing the overlap issue! I'll go ahead and add it here instead of following up like originally planned.
