### PR TITLE
Fix table/plots not updating correctly on windows

### LINKED ISSUE #3102: Plots don't update while experiment is running
Testing on Windows (since there were complaints on Discord):

https://user-images.githubusercontent.com/3659196/212574986-f2192d45-f80e-4c02-b6f8-45c55dc4f74e.mov

```
C:\Users\ivan\miniconda3\envs\hackathon\python.exe -m dvc plots diff -o .dvc\tmp\plots --split --json - COMPLETED (4569ms)
[version: 0.5.36, 2023-01-16T00:00:41.591Z, pid: 12768] > C:\Users\ivan\miniconda3\envs\hackathon\python.exe -m dvc data status --granular --unchanged --json - COMPLETED (6199ms)
[version: 0.5.36, 2023-01-16T00:06:58.263Z, pid: 13040] > C:\Users\ivan\miniconda3\envs\hackathon\python.exe -m dvc plots diff 4c6f1b2 workspace -o .dvc\tmp\plots --split --json - INITIALIZED
[version: 0.5.36, 2023-01-16T00:07:08.138Z, pid: 13040] > C:\Users\ivan\miniconda3\envs\hackathon\python.exe -m dvc plots diff 4c6f1b2 workspace -o .dvc\tmp\plots --split --json - COMPLETED (9891ms)
```

```
DVC version: 2.41.1 (pip)
---------------------------------
Platform: Python 3.10.8 on Windows-10-10.0.22621-SP0
Subprojects:
        dvc_data = 0.29.0
        dvc_objects = 0.14.1
        dvc_render = 0.0.17
        dvc_task = 0.1.9
        dvclive = 1.3.2
        scmrepo = 0.1.5
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: https
Workspace directory: NTFS on C:\
Repo: dvc, git
```

### LINKED ISSUE #3103: Table is not refreshed after experiment is removed
On Windows, conda, VS Code 1.74.3, extension 0.5.36:

https://user-images.githubusercontent.com/3659196/212576087-b247156c-8914-4b69-8112-4e6177a402cf.mov

```
[version: 0.5.36, 2023-01-16T00:32:31.286Z, pid: 4972] > C:\Users\ivan\miniconda3\envs\hackathon\python.exe -m dvc exp remove picky-wads - COMPLETED (1133ms)
```

```
DVC version: 2.41.1 (pip)
---------------------------------
Platform: Python 3.10.8 on Windows-10-10.0.22621-SP0
Subprojects:
        dvc_data = 0.29.0
        dvc_objects = 0.14.1
        dvc_render = 0.0.17
        dvc_task = 0.1.9
        dvclive = 1.3.2
        scmrepo = 0.1.5
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: https
Workspace directory: NTFS on C:\
Repo: dvc, git
```

### PR DESCRIPTION
**Pull request by julieg18**
## Demo

https://user-images.githubusercontent.com/43496356/215863127-cddd364f-5b42-4972-ab51-bc2677eb2f9b.mp4

Fixes #3103, fixes #3102

### CODE REVIEW

File: extension/src/fileSystem/watcher.ts [hunk 1]
```diff
@@ -9,17 +15,26 @@ const getRelativePatternForOutsideWorkspace = (
...
 ): RelativePattern => new RelativePattern(uri, pattern)
 
+const createRelativePattern = (
+  folder: WorkspaceFolder,
+  path: string,
+  pattern: string
+) => {
+  return new RelativePattern(
+    folder,
+    `${path}${path.length > 0 ? '/' : ''}${pattern}`
```
Comment (julieg18) [inline extension/src/fileSystem/watcher.ts:25]: Is there a simpler way to get the pattern joined?

File: extension/src/fileSystem/watcher.ts [hunk 2]
```diff
@@ -9,17 +15,26 @@ const getRelativePatternForOutsideWorkspace = (
...
 export const getRelativePattern = (
   path: string,
   pattern: string
 ): RelativePattern => {
   for (const workspaceFolder of workspace.workspaceFolders || []) {
     const workspaceFolderPath = workspaceFolder.uri.fsPath
     if (isSameOrChild(workspaceFolderPath, path)) {
-      return new RelativePattern(
-        workspaceFolder,
-        join(relative(workspaceFolderPath, path), pattern)
```
Comment (julieg18) [inline extension/src/fileSystem/watcher.ts:21]: Took wayyyy too long for me to realize this, but `RelativePattern` requires the `pattern` to be created with forward slashes 🤦. `join` will add backward slashes in a windows environment, thus breaking things in windows.

File: extension/src/fileSystem/watcher.ts [hunk 3]
```diff
@@ -18,7 +19,7 @@ export const getRelativePattern = (
     if (isSameOrChild(workspaceFolderPath, path)) {
       return new RelativePattern(
         workspaceFolder,
-        join(relative(workspaceFolderPath, path), pattern)
+        joinWithForwardSlashes([relative(workspaceFolderPath, path), pattern])
```
Comment (mattseddon) [inline extension/src/fileSystem/watcher.ts:22]: [Q] Can we create a new relativePattern file and move `joinWithForwardSlashes` and these function in there? Grouping the behaviour/functions together would give more clues about why it was done in the future.  

[I] Would be good to get a regression test for the behaviour (maybe add to `'should watch the .git directory for updates'` in `extension/src/test/suite/experiments/data/index.test.ts`).

File: extension/src/test/suite/fileSystem/watcher.test.ts [hunk 4]
```diff
@@ -27,7 +28,9 @@ suite('File System Watcher Test Suite', () => {
       expect(relativePattern.baseUri).to.deep.equal(
         getTestWorkspaceFolder().uri
       )
-      expect(relativePattern.pattern).equal(join('.git', '**'))
+      expect(relativePattern.pattern).equal(
+        joinWithForwardSlashes(['.git', '**'])
```
Comment (mattseddon) [inline extension/src/test/suite/fileSystem/watcher.test.ts:32]: [C] Maybe don't use the function here as a change to the function could break the required behaviour but the test will still pass.

**Review by mattseddon — APPROVED** [review]

**Comment by mattseddon** [comment]
[Q] Can you confirm if this also fixes #3102

**Review by sroy3 — APPROVED** [review]

**Comment by julieg18** [comment]
> [Q] Can you confirm if this also fixes https://github.com/iterative/vscode-dvc/issues/3102

Look like it does fix the issue!

File: extension/src/fileSystem/watcher.ts (hunk 3 above)
Comment (julieg18) [reply extension/src/fileSystem/watcher.ts]: > [Q] Can we create a new relativePattern file and move joinWithForwardSlashes and these function in there? Grouping the behaviour/functions together would give more clues about why it was done in the future.

Done!

> [I] Would be good to get a regression test for the behaviour (maybe add to 'should watch the .git directory for updates' in extension/src/test/suite/experiments/data/index.test.ts).

Currently, we have a `.git` file watcher test set up for when the `.git` folder is outside of the workspace since that's how our `demo` project works. But I couldn't think of an uncomplicated way to test a workspace that has a local `.git` folder inside since we don't have a project like that in our repo... Is there something I'm misunderstanding/missing?

**Comment by julieg18** [comment]
Going to go ahead and merge this! If we need more testing, I'll do so in a followup :)

File: extension/src/fileSystem/watcher.ts (hunk 3 above)
Comment (mattseddon) [reply extension/src/fileSystem/watcher.ts]: not sure but can we create a set of nested subfolders inside of the demo project and then stub `getGitRepositoryRoot` to return that path or even stub `getGitPath`? Could then remove the top directory at the end of the test

Comment (julieg18) [reply extension/src/fileSystem/watcher.ts]: > not sure but can we create a set of nested subfolders inside of the demo project and then stub getGitRepositoryRoot to return that path or even stub getGitPath? Could then remove the top directory at the end of the test

Will work on it in a followup!
