### PR TITLE
Fix Windows repo file watcher using RelativePattern

### LINKED ISSUE #1904: Glob pattern '**' does not work with createFileSystemWatcher on Windows
`**` will only look one level deep
`**/**` or `**/*.*` two level deep and so on.
 We need to replace it with something that works recursively on Windows.

Issue found in example repo in this thread:
https://discord.com/channels/485586884165107732/842220310585147452/986436373756141609

### PR DESCRIPTION
**Pull request by sroy3**
Fixes #1904 

https://user-images.githubusercontent.com/3683420/173858554-4f28f12f-1f6a-4b74-8497-3d6a52e678c2.mp4

### CODE REVIEW

**Review by rogermparent — APPROVED** [review]

File: extension/src/repository/data/index.ts [hunk 1]
```diff
@@ -141,12 +141,15 @@ export class RepositoryData extends DeferredDisposable {
     const gitRoot = await getGitRepositoryRoot(this.dvcRoot)
 
     this.dispose.track(
-      createFileSystemWatcher(join(this.dvcRoot, '**'), (path: string) => {
-        if (isExcluded(this.dvcRoot, path)) {
-          return
+      createFileSystemWatcher(
+        new RelativePattern(this.dvcRoot, '**/*.*'),
```
Comment (rogermparent) [inline extension/src/repository/data/index.ts:145]: Will this have issues with files that don't have an extension? Would `**/*` work?
