### PR TITLE
Fix "Image By Step" step number inaccuracy

### LINKED ISSUE #4492: Wrong step number in batched images
Mind the numbers 1,2,3,40,41,42 in the directory that is being plotted.

https://github.com/iterative/vscode-dvc/assets/3659196/8b39e71f-dd7f-4e24-b02c-48b6a09cbb53

### PR DESCRIPTION
**Pull request by julieg18**
## Demo

https://github.com/iterative/vscode-dvc/assets/43496356/70942e16-0c9a-4915-95cb-f547a6de3b34

Fixes #4492

### CODE REVIEW

File: webview/src/plots/components/comparisonTable/cell/ComparisonTableMultiCell.tsx [hunk 1]
```diff
@@ -76,7 +79,7 @@ export const ComparisonTableMultiCell: React.FC<{
             setCurrentStep(Number(event.target.value))
           }}
         />
-        <p>{currentStep}</p>
+        <p>{selectedImg?.ind}</p>
```
Comment (mattseddon) [inline webview/src/plots/components/comparisonTable/cell/ComparisonTableMultiCell.tsx:82]: [Q] Can this actually be undefined? Do we need the optional chain and should we show something instead of undefined if that can actually happen?

**Review by mattseddon — APPROVED** [review]

File: webview/src/plots/components/comparisonTable/cell/ComparisonTableMultiCell.tsx (hunk 1 above)
Comment (julieg18) [reply webview/src/plots/components/comparisonTable/cell/ComparisonTableMultiCell.tsx:82]: If I'm understanding your question, should not be possible for `ind` to be undefined. Just a typo on my part :)
